spring:
  datasource:
    url: jdbc:h2:file:./data/checklist-app-db
    driverClassName: org.h2.Driver
    username: diego
    password: 1234
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

h2:
  console:
    enabled: true
    path: /h2-console
